POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvcnBwaWtvdGthIiwiaWQiOiI2ODExZWFlMWM5OGNlMDVhNjcyZWQ2ZjkiLCJpYXQiOjE3NDYxNzY2MDJ9.YJ5SQV192PNcE0jsbuTA6xmKAjJ6N9dFpzbvzqaD8YQ

{
    "title": "Koirat",
    "author": "Urho Lab",
    "url": "dogs.com",
    "likes": 2
}